### ISSUE TITLE
nasapower appears in Suggests but doesn't appear to be used in package

### ISSUE THREAD

**Issue by adamhsparks** [AgrDataSci/gosset#24]
I'm just doing some revdep checks and I'm getting an error for *gosset*, seemingly because *gosset* has *nasapower* as a "Suggests" package, but I'm unable to find where it's actually used in the package anywhere. Is this correct? Should it be removed from the "Suggests" and Vignette's bibliography file?

**Comment by kauedesousa** [comment]
I fixed it here https://github.com/AgrDataSci/gosset/commit/65195dd3b000fad8a6c3ae623ad610ae6ec6c00a. I just to do some tests before sending a new version to CRAN
