### ISSUE TITLE
rank_binomial vs break_rank

### ISSUE THREAD

**Issue by kauedesousa** [AgrDataSci/gosset#26]
Hi @dbrownf, 

I see that you renamed the function `rank_binomial()` to `break_rank()` here https://github.com/AgrDataSci/gosset/commit/05533e73436065cd35a528f6ea46f6639a9b37a4. I would like to know your thoughts about this change. The function had this name to match with the nomenclature used here https://doi.org/10.18637/jss.v048.i09. They called "binomial frequencies". Also to match with the other rank functions `rank_tricot()`, `rank_paircomp()` and `rank_numeric()`

**Comment by jacobvanetten** [comment]
This is based on my suggestion, probably based on ignorance.

Does the function create a table of binomial frequencies or does it break
down the rankings to make them pairwise?

If the output is a table of binomial frequencies, I suggest
rank_binomialfreq. A bit long, but clear.

**Comment by dbrownf** [comment]
Hi @kauedesousa,

Apologies for the direct commit, I will do a pull request next time. The reasoning about the change is actually to be consistent with the other functions. For instance, rank_numeric takes a numeric input and transform it into a ranking, rank_tricot takes tricot data as input and transform it into a ranking. If that logic holds for rank_binomial one would expect that it would take a binomial input and then transform it into a ranking, but I think this is actually not the case.

**Comment by kauedesousa** [comment]
Binomial frequencies that can be either for the whole tournament or by each encounter. 

```
library("gosset")
library("PlackettLuce")

R <- matrix(c(1, 2, 0, 0,
              4, 1, 2, 3,
              2, 4, 3, 1,
              1, 2, 3, 0,
              2, 1, 1, 0,
              1, 0, 3, 2), nrow = 6, byrow = TRUE)
colnames(R) <- c("apple", "banana", "orange", "pear")

R <- as.rankings(R)

rank_binomial(R)
```

```
  player1 player2 win1 win2
1   apple  banana    3    2
2   apple  orange    3    2
3  banana  orange    2    1
4   apple    pear    1    2
5  banana    pear    1    1
6  orange    pear    1    2
```


```

rank_binomial(R, disaggregate = TRUE)

```

```
    id player1 player2 win1 win2
1   1   apple  banana    1    0
2   2   apple  banana    0    1
3   2   apple  orange    0    1
4   2  banana  orange    1    0
5   2   apple    pear    0    1
6   2  banana    pear    1    0
7   2  orange    pear    1    0
```

**Comment by kauedesousa** [comment]
I see the discussion on this issue in the ms comments. Now I understand your idea and I agree with it. But to keep consistency with the sister function (rank_paircomp) which does a similar thing (uses PL ranking as input and set to a different order) I suggest `set_binomialfreq()` and `set_paircomp()`

This could be done with `as.binomialfreq()` and `as.paircomp()` as well. What do you think?

**Comment by jacobvanetten** [comment]
Both work. The important thing was that we understand the issue. The
solution is your decision :-)
